# ========================
# Clash-ALL ä¼˜åŒ–é…ç½®
# ========================

# æœºåœºèŠ‚ç‚¹è®¢é˜…

proxy-providers:
  Airport:
    type: http
    interval: 3600
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: DIRECT
    url: "https://sub.voxelcat.net:16666/CKg3abstVnOeRpm1aB5G/download/collection/Mihomo?target=ClashMeta"
    #override:
    #  additional-prefix: "[å®ˆå€™ç½‘ç»œ] " # ç»™æ­¤æœºåœºæœºåœº-Bçš„èŠ‚ç‚¹å¤´éƒ¨åŠ åå­—ï¼Œå¼•å·å†…åå­—å¯ä»¥æ”¹ã€‚
  

# èŠ‚ç‚¹ä¿¡æ¯
proxies:
  - {name: ç›´è¿, type: direct}
  - {name: æ‹’ç», type: reject}

# å…¨å±€é…ç½® 
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
allow-lan: true
bind-address: "*"
ipv6: true
unified-delay: true
tcp-concurrent: true
log-level: warning
find-process-mode: 'off'
# interface-name: en0
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 15
disable-keep-alive: false
profile:
  store-selected: true
  store-fake-ip: true

# æ§åˆ¶é¢æ¿
external-controller: 0.0.0.0:9090
secret: ""
external-ui: "/etc/mihomo/run/ui"
external-ui-name: zashboard
external-ui-url: "https://github.voxelcat.net/https://github.voxelcat.net/https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"

# å—…æ¢
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain:
    - "+.baidu.com"

# å…¥ç«™  
tun:
  enable: true
  # system/gvisor/mixed
  stack: mixed
  dns-hijack: ["any:53", "tcp://any:53"]
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

# DNSæ¨¡å—
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  respect-rules: true
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:private_domain,cn_domain"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - "time.*.com"
  pr-nameserver:
    - 223.5.5.5
  proxy-server-nameserver:
    - https://223.5.5.5/dns-query
  # nameseverå°½é‡ç”¨è¿è¥å•†æä¾›çš„DNS
  nameserver:
    - 202.96.134.33
    - 202.96.128.86
    
# å‡ºç«™ç­–ç•¥
# æ³¨æ„é”šç‚¹å¿…é¡»æ”¾åœ¨å¼•ç”¨çš„ä¸Šæ–¹ï¼Œå¯ä»¥é›†ä¸­æŠŠé”šç‚¹å…¨éƒ¨æ”¾yamlçš„é¡¶éƒ¨ã€‚
pr: &pr {type: select, proxies: [ç›´è¿, æ‰€æœ‰-æ‰‹åŠ¨, æ‰€æœ‰-è‡ªåŠ¨, é¦™æ¸¯-æ•…è½¬, é¦™æ¸¯-è‡ªåŠ¨, å°æ¹¾-æ•…è½¬, å°æ¹¾-è‡ªåŠ¨, æ—¥æœ¬-æ•…è½¬, æ–°åŠ å¡-æ•…è½¬, æ–°åŠ å¡-è‡ªåŠ¨, éŸ©å›½-æ•…è½¬,  éŸ©å›½-è‡ªåŠ¨, ç¾å›½-æ•…è½¬, è‹±å›½-æ•…è½¬, å…¶ä»–-æ•…è½¬, æµåª’ä½“-æ‰‹åŠ¨, æµåª’ä½“-è‡ªåŠ¨, é“¾å¼è½åœ°, æ‹’ç»]}

proxy-groups:
# ========================
# ä¸šåŠ¡åˆ†æµç»„
# ========================
  - {name: AI, <<: *pr, icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/ChatGPT.png"}
  - {name: GitHub, <<: *pr, icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/GitHub.png"}
  - {name: Apple, <<: *pr, icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Apple.png"}
  - {name: Microsoft, <<: *pr, icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Microsoft.png"}
  - {name: Stream Media, <<: *pr, icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Netflix_b.png"}
  - {name: PayPal,  <<: *pr, icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/PayPal_business.png"}
  - {name: Steam, <<: *pr, icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Steam.png"}
  - {name: Test, <<: *pr, icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Flight.png"}
  - {name: å›½å¤–, <<: *pr, icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Omission.png"}
  - {name: å›½å†…, <<: *pr, icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/China.png"}
  - {name: å…¶ä»–, <<: *pr, icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Omission.png"}

# ========================
# èŠ‚ç‚¹ç»„ (å·²ä¼˜åŒ–æ•…è½¬é€»è¾‘)
# ========================
 
  - {name: æ‰€æœ‰-æ‰‹åŠ¨, type: select, include-all: true, filter: "^((?!(ç›´è¿|æ‹’ç»)).)*$", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Global.png"}
  - {name: æ‰€æœ‰-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "^((?!(ç›´è¿|æ‹’ç»)).)*$", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Global.png"}

  # é¦™æ¸¯
  - {name: é¦™æ¸¯-æ•…è½¬, type: fallback, include-all: true, url: "http://www.gstatic.com/generate_204", interval: 300, lazy: true, filter: "(?i)å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Hong_Kong.png"}
  - {name: é¦™æ¸¯-æ‰‹åŠ¨, type: select, include-all: true, filter: "(?i)å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Hong_Kong.png"}   
  - {name: é¦™æ¸¯-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?i)å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Hong_Kong.png"}

  # å°æ¹¾
  - {name: å°æ¹¾-æ•…è½¬, type: fallback, include-all: true, url: "http://www.gstatic.com/generate_204", interval: 300, lazy: true, filter: "(?i)å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|Taiwan", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/China_Taipei.png"}
  - {name: å°æ¹¾-æ‰‹åŠ¨, type: select, include-all: true, filter: "(?i)å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|Taiwan", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/China_Taipei.png"}   
  - {name: å°æ¹¾-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?i)å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|Taiwan", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/China_Taipei.png"}

  # æ—¥æœ¬
  - {name: æ—¥æœ¬-æ•…è½¬, type: fallback, include-all: true, url: "http://www.gstatic.com/generate_204", interval: 300, lazy: true, filter: "(?i)å¹¿æ—¥|æ—¥æœ¬|JP|ä¸œäº¬|å¤§é˜ª|ğŸ‡¯ğŸ‡µ|Japan", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Japan.png"}
  - {name: æ—¥æœ¬-æ‰‹åŠ¨, type: select, include-all: true, filter: "(?i)å¹¿æ—¥|æ—¥æœ¬|JP|ä¸œäº¬|å¤§é˜ª|ğŸ‡¯ğŸ‡µ|Japan", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Japan.png"}   
  - {name: æ—¥æœ¬-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?i)å¹¿æ—¥|æ—¥æœ¬|JP|ä¸œäº¬|å¤§é˜ª|ğŸ‡¯ğŸ‡µ|Japan", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Japan.png"}

  # æ–°åŠ å¡
  - {name: æ–°åŠ å¡-æ•…è½¬, type: fallback, include-all: true, url: "http://www.gstatic.com/generate_204", interval: 300, lazy: true, filter: "(?i)å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Singapore.png"}
  - {name: æ–°åŠ å¡-æ‰‹åŠ¨, type: select, include-all: true, filter: "(?i)å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Singapore.png"}   
  - {name: æ–°åŠ å¡-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?i)å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Singapore.png"}

  # éŸ©å›½
  - {name: éŸ©å›½-æ•…è½¬, type: fallback, include-all: true, url: "http://www.gstatic.com/generate_204", interval: 300, lazy: true, filter: "(?i)å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|ğŸ‡°ğŸ‡·|Korea", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/South_Korea.png"}
  - {name: éŸ©å›½-æ‰‹åŠ¨, type: select, include-all: true, filter: "(?i)å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|ğŸ‡°ğŸ‡·|Korea", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/South_Korea.png"}   
  - {name: éŸ©å›½-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?i)å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|ğŸ‡°ğŸ‡·|Korea", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/South_Korea.png"}

  # ç¾å›½
  - {name: ç¾å›½-æ•…è½¬, type: fallback, include-all: true, url: "http://www.gstatic.com/generate_204", interval: 300, lazy: true, filter: "(?i)å¹¿ç¾|ç¾|US|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|è¥¿é›…å›¾|ğŸ‡ºğŸ‡¸|United States", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/USA.png"}
  - {name: ç¾å›½-æ‰‹åŠ¨, type: select, include-all: true, filter: "(?i)å¹¿ç¾|ç¾|US|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|è¥¿é›…å›¾|ğŸ‡ºğŸ‡¸|United States", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/USA.png"}   
  - {name: ç¾å›½-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?i)å¹¿ç¾|ç¾|US|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|è¥¿é›…å›¾|ğŸ‡ºğŸ‡¸|United States", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/USA.png"}

  # è‹±å›½
  - {name: è‹±å›½-æ•…è½¬, type: fallback, include-all: true, url: "http://www.gstatic.com/generate_204", interval: 300, lazy: true, filter: "(?i)è‹±å›½|è‹±|ä¼¦æ•¦|UK|United Kingdom|ğŸ‡¬ğŸ‡§", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/UK.png"}
  - {name: è‹±å›½-æ‰‹åŠ¨, type: select, include-all: true, filter: "(?i)è‹±å›½|è‹±|ä¼¦æ•¦|UK|United Kingdom|ğŸ‡¬ğŸ‡§", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/UK.png"}   
  - {name: è‹±å›½-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?i)è‹±å›½|è‹±|ä¼¦æ•¦|UK|United Kingdom|ğŸ‡¬ğŸ‡§", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/UK.png"}

  # å…¶ä»–
  - {name: å…¶ä»–-æ•…è½¬, type: fallback, include-all: true, url: "http://www.gstatic.com/generate_204", interval: 300, lazy: true, filter: "^((?!(ç›´è¿|æ‹’ç»|å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|å¹¿å°|å°æ¹¾|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|å¹¿æ—¥|æ—¥æœ¬|JP|ä¸œäº¬|å¤§é˜ª|ğŸ‡¯ğŸ‡µ|å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ğŸ‡¸ğŸ‡¬|å¹¿éŸ©|éŸ©å›½|KR|é¦–å°”|ğŸ‡°ğŸ‡·|å¹¿ç¾|ç¾|US|çº½çº¦|ğŸ‡ºğŸ‡¸|è‹±å›½|UK|ğŸ‡¬ğŸ‡§)).)*$", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/UK.png"}
  - {name: å…¶ä»–-æ‰‹åŠ¨, type: select, include-all: true, filter: "^((?!(ç›´è¿|æ‹’ç»|å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|å¹¿å°|å°æ¹¾|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|å¹¿æ—¥|æ—¥æœ¬|JP|ä¸œäº¬|å¤§é˜ª|ğŸ‡¯ğŸ‡µ|å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ğŸ‡¸ğŸ‡¬|å¹¿éŸ©|éŸ©å›½|KR|é¦–å°”|ğŸ‡°ğŸ‡·|å¹¿ç¾|ç¾|US|çº½çº¦|ğŸ‡ºğŸ‡¸|è‹±å›½|UK|ğŸ‡¬ğŸ‡§)).)*$", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/UK.png"}   
  - {name: å…¶ä»–-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "^((?!(ç›´è¿|æ‹’ç»|å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|å¹¿å°|å°æ¹¾|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|å¹¿æ—¥|æ—¥æœ¬|JP|ä¸œäº¬|å¤§é˜ª|ğŸ‡¯ğŸ‡µ|å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ğŸ‡¸ğŸ‡¬|å¹¿éŸ©|éŸ©å›½|KR|é¦–å°”|ğŸ‡°ğŸ‡·|å¹¿ç¾|ç¾|US|çº½çº¦|ğŸ‡ºğŸ‡¸|è‹±å›½|UK|ğŸ‡¬ğŸ‡§)).)*$", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/UK.png"}
  
  # æµåª’ä½“
  - {name: æµåª’ä½“-æ•…è½¬, type: fallback, include-all: true, url: "http://www.gstatic.com/generate_204", interval: 300, lazy: true, filter: "(?i)0.2x|0.5x|å®éªŒæ€§", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Netflix_b.png"}
  - {name: æµåª’ä½“-æ‰‹åŠ¨, type: select, include-all: true, filter: "(?i)0.2x|0.5x|å®éªŒæ€§", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Netflix_b.png"}
  - {name: æµåª’ä½“-è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 50, interval: 300, filter: "(?i)0.2x|0.5x|å®éªŒæ€§", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Netflix_b.png"}

  - {name: é“¾å¼è½åœ°, type: select, include-all: true, filter: "(?=.*(é“¾å¼)).*$", icon: "https://github.voxelcat.net/https://raw.githubusercontent.com/Vbaethon/HOMOMIX/main/Icon/Color/Global.png"}

# ========================
# è§„åˆ™å¼•æ“ï¼ˆrulesï¼‰
# ========================
rules:
  - DOMAIN-SUFFIX,023168.xyz, Stream Media 
  - DOMAIN-SUFFIX,niceduck.lol, Stream Media
  - DOMAIN-SUFFIX,sexemby.com, Stream Media
  - DOMAIN-SUFFIX,cn2gias.uk, Stream Media
  - DOMAIN-SUFFIX,myip.ipip.net, å›½å†…
  - DOMAIN-SUFFIX,r.inews.qq.com, å›½å†…
  - DOMAIN-SUFFIX,ldvfx.com, å›½å†…
  - DOMAIN-SUFFIX,weimaosheji.com, å›½å†…
  - DOMAIN-SUFFIX,qichiyu.com, å…¶ä»–
  - RULE-SET,ai, AI
  - RULE-SET,github_domain,GitHub
  - RULE-SET,apple_domain,Apple
  - RULE-SET,apple-CN_domain,Apple  
  - RULE-SET,microsoft_domain,Microsoft
  - RULE-SET,tiktok_domain,Stream Media
  - RULE-SET,netflix_domain,Stream Media
  - RULE-SET,netflix_ip,Stream Media,no-resolve
  - RULE-SET,disney_domain,Stream Media
  - RULE-SET,hbo_domain,Stream Media
  - RULE-SET,amazon_domain,Stream Media
  - RULE-SET,spotify_domain,Stream Media
  - RULE-SET,paypal_domain, PayPal
  - RULE-SET,steam_domain,Steam
  - RULE-SET,epic_domain,Steam
  - RULE-SET,test_domain,Test
  - RULE-SET,proxy_domain,å…¶ä»–
  - RULE-SET,globe_domain,å›½å¤–  
  - RULE-SET,direct_domain,å›½å†…
  - RULE-SET,cn_domain,ç›´è¿
  - RULE-SET,cn_ip,ç›´è¿,no-resolve
  - RULE-SET,private_domain,ç›´è¿
  - MATCH,å…¶ä»–
 # - RULE-SET,youtube_domain,YouTube
 # - RULE-SET,google_domain,Google
 # - RULE-SET,google_ip,Google,no-resolve
 # - RULE-SET,telegram_domain,Telegram
 # - RULE-SET,telegram_ip,Telegram,no-resolve
 # - RULE-SET,twitter_domain,Twitter(X)
 # - RULE-SET,facebook_domain,Facebook
 # - RULE-SET,gfw_domain, å…¶ä»–
 # - RULE-SET,geolocation-!cn, å…¶ä»–


# ========================
# è§„åˆ™é›†æä¾›è€…
# ========================
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}

rule-providers:
  ai: {  <<: *domain, url: "https://github.voxelcat.net/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ai-!cn.mrs" }
  github_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs"}
  apple_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs"} 
  apple-CN_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-cn.mrs"}
  microsoft_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs"}
  tiktok_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/tiktok.mrs"}
  netflix_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/netflix.mrs"}
  netflix_ip: {<<: *ip, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/netflix.mrs"}
  disney_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/disney.mrs"}
  hbo_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/hbo.mrs"}
  amazon_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/amazon.mrs"}
  spotify_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs"}
  paypal_domain: { <<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
  steam_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/steam.mrs"}
  epic_domain: {<<: *class, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list"}
  test_domain: {<<: *class, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Check.list"}
  proxy_domain: {<<: *class, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Proxy.list"}
  globe_domain: {<<: *class, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list"} 
  direct_domain: {<<: *class, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Direct.list"}
  cn_domain: { <<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs"}
  cn_ip: { <<: *ip, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs"}
  private_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs"}
 # youtube_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs"}
 # google_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs"}
 # google_ip: {<<: *ip, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/google.mrs"}
 # telegram_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/telegram.mrs"}
 # telegram_ip: {<<: *ip, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs"}
 # twitter_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/x.mrs"}
 # facebook_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/facebook.mrs"}
 # geolocation-!cn: { <<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.mrs"}
 # gfw_domain: {<<: *domain, url: "https://github.voxelcat.net/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs"}